### ISSUE TITLE
Component cannot find import

### ISSUE THREAD

**Issue by mphasize** [kennethkalmer/ember-cli-nouislider#1]
Hi, 

I'm trying to follow the README for extending the `range-slider` component, unfortunately I am getting an error:

`Could not find module `ember-cli-nouislider/components/range-slider`

I'm using Ember 1.11.1 and ember-cli 2.3.

Any ideas how to solve this issue?

(Btw. I can perfectly use the `range-slider` component from the addon in my application, I just cannot import it for extending...)

**Comment by kennethkalmer** [comment]
Thanks for reporting! I'll have a look later today, my plan is to hook up ember-many to ensure I'm testing against a lot of different versions and remain compatible.

**Comment by kennethkalmer** [comment]
Busy upgrading the underlying ember-cli version used to built the project with to 0.2.3, and some other general maintenance and hoping to sort this out as part of the general housecleaning...

**Comment by kennethkalmer** [comment]
Just waiting on travis, things should be good for a new release momentarily

**Comment by kennethkalmer** [comment]
@mphasize thanks for trying out ember-cli-nouislider and reporting the issue!

**Comment by mphasize** [comment]
Thanks for fixing it so fast!
