### ISSUE TITLE
Not all NoUISlider options are supported

### ISSUE THREAD

**Issue by davidgoli** [kennethkalmer/ember-cli-nouislider#12]
Missing at least `format` and `pips`

http://refreshless.com/nouislider/slider-read-write/
http://refreshless.com/nouislider/pips/

**Comment by kennethkalmer** [comment]
Closing thanks to your wonderful contribution in #13. Just adding a note that `get` and `set` should be handled by bindings/actions as it currently is... Unless I'm missing totally obvious :grin:
