### ISSUE TITLE
1.13/2.0 Support

### ISSUE THREAD

**Issue by knownasilya** [kennethkalmer/ember-cli-nouislider#15]
Mainly it's the new computed property syntax. But maybe we should wait for Ember 2.0 to see what else gets removed/changed.

Would require a major version bump.

**Comment by kennethkalmer** [comment]
This might be a good thing to mark a 1.0 release.

**Comment by kennethkalmer** [comment]
I pushed out 0.7.0 last night and all the tests pass just fine. Given the regressions fixed by #18 and #19 it might be better (for me) to have some integration tests in place before making it a 1.0 solid.

**Comment by kennethkalmer** [comment]
I just released 0.8.0 based on ember-cli 2.4.2 and everything looks perfectly healthy. `ember-try` keeps testing against 1.13 to ensure that is covered.

Going to close this for now.
