### ISSUE TITLE
[Question] Slider won't show up

### ISSUE THREAD

**Issue by brenoinojosa** [kennethkalmer/ember-cli-nouislider#17]
Hi,

I'm new to ember and just came across nouislider (really neat plugin btw ).
So, I did install ember-cli-nouislider via ember install ember-cli-nouislider
Then I included it in my .hbs like this: {{range-slider start=13 range=100 start=0 connect="lower" behavior="drag" change="changedAction"}}

Should it show up automatically or do I need to change something else? I followed every step but it seems it's buggy for some reason.
Nothing is showing up right now except for a div with an ember id.

Versions: I have everything up to date (bower, ember, etc.).

Can you give me some help?
Thank you.

**Comment by kennethkalmer** [comment]
Hi @brenoinojosa, apologies for not getting back sooner! Did you manage?

**Comment by brenoinojosa** [comment]
Yeah, fortunately, I did manage to get it to work :)
I was just new to Ember haha. Thanks for the reply.

**Comment by kennethkalmer** [comment]
No worries :)
