### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by IsaiahJTurner** [kennethkalmer/ember-cli-nouislider#20]
For example, how can I bind the slider value to a property on my controller that when the controllers property changes, updates the slider. And, how can I use the `connect` property of the slider?

**Comment by IsaiahJTurner** [comment]
Update: I'm crazy. The documentation was so good I didn't realize it was rewritten for Ember.

**Comment by kennethkalmer** [comment]
@IsaiahJTurner thanks! Just a quick note, I was thinking of changing the color scheme to be more inline with Ember (ie, orange shades) so it is more distinct.

**Comment by allthesignals** [comment]
Question on this: do I need to manage updating properties with a component action? Or is it possible to bind the properties to the slider? Sorry if this is already covered in the docs.
