### ISSUE TITLE
How to set style / class on slider?

### ISSUE THREAD

**Issue by samsebastian** [kennethkalmer/ember-cli-nouislider#23]
Is there a way or option to add classes to the slider element? ie `bg-success` etc?

I have a slider where the color of the bar needs to change based on the value of the slider, which I was able to do via jquery, but not sure how to pass it into the component in Ember?

Thanks :+1:

**Comment by kennethkalmer** [comment]
Sorry for the late reply! What do you think would make for a good API to do this?

**Comment by samsebastian** [comment]
Not sure about how to specifically do it within Noui but what I was aiming to do was just set the color via a computed property or something and then pass that property into the element? So even just something that was like `{{range-slider start=contact.rating step=5 change="change" classes="bg-success foo-class bar-class"}}` or something that appended the property to the classes in the slider?
That way if it needs to change you could just pass `classes=silderClasses` and Ember computed property would deal with the rest?

**Comment by kennethkalmer** [comment]
@samsebastian could you see if #57 resolves this issues for you? It has been published as part of 1.0.0-rc.2 (`ember install ember-cli-nouislider@next`). Please feel free to close the issue if this does what you need.

**Comment by markgulisao** [comment]
Hi is there a way to change the slider icon into fa fa-calendar-plus-o icon for example? 
or include icons such as this within the slider bar itself?
