### ISSUE TITLE
Default formatting functions break negative ranges

### ISSUE THREAD

**Issue by Ramblurr** [kennethkalmer/ember-cli-nouislider#24]
The addon provides two default [format functions](https://github.com/kennethkalmer/ember-cli-nouislider/blob/773c52e2ba7d3cf344128d64501f57a866e6bced/addon/components/range-slider.js#L37) that by default just return the value they are passed. 

This unfortunately breaks when a range has a negative component (e.g, min: -5, max: 5).

This is because nouislider's `setValues` function [casts the value to set the handle to into a string](https://github.com/leongersen/noUiSlider/blob/2fbb5e21809a27acdc5b8f5f2c09acc1c1c5197d/src/js/scope.js#L94) before calling `formatFrom`. However the expect the value returned from the format.from function to be a Number.

But, the result with this addon's default format functions is to return the string.

In my app overriding the formatFrom function to be something like the following fixed the issue.

```
formatFrom(value) {
  return +value;
}
```

I'm not sure if this issue is a bug per-se, as it is more of an unexpected behavior. If it doesn't require code changes, then at least adding a note to the documentation would be helpful.

**Comment by sandinosaso** [comment]
@Ramblurr Thank you this helped me with the same problem.

**Comment by kennethkalmer** [comment]
Sorry for letting this one sit so long, got merged into master via #43. Expect a release shortly

**Comment by kennethkalmer** [comment]
v0.12.0 has just been released, thanks for your contributions!
