### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by sandinosaso** [kennethkalmer/ember-cli-nouislider#27]
I am getting these deprecation warnings:

`DEPRECATION: A property of <project@view:-outlet::ember817> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation. [deprecation id: ember-views.dispatching-modify-property]`

My environment:

```
ember-cli: 2.5.1
node: 4.1.1
os: darwin x64
```

**Comment by kennethkalmer** [comment]
Thanks, will have a look!

**Comment by kennethkalmer** [comment]
I think this got resolved in #39 and just released in v0.12.0. If you're still getting these issues then please reopen the issue.

Thanks for reporting and helping to improve the addon!
