### ISSUE TITLE
Update the value as dragging changes

### ISSUE THREAD

**Issue by Blackening999** [kennethkalmer/ember-cli-nouislider#28]
Hey!
Nice plugin, however, it lacks of handler for "update" event. I want to show the sliding results instantly, like it is in original one:

```js
// When the slider value changes, update the input and span
range.noUiSlider.on('update', function( values, handle ) {
	if ( handle ) {
		valueInput.value = values[handle];
	} else {
		valueSpan.innerHTML = values[handle];
	}
});
```

source : http://refreshless.com/nouislider/

**Comment by kennethkalmer** [comment]
Thanks for the kind words!

The documentation is a bit lacking, sorry! But the event has been supported since 773c52e2.

**Comment by Blackening999** [comment]
Thanks for update!
