### ISSUE TITLE
Support for "set" and "slide" events

### ISSUE THREAD

**Issue by timrwilliams** [kennethkalmer/ember-cli-nouislider#3]
Hi Kenneth, thanks a lot for packaging this. I think its worth adding in support for the **set** and **slide** events from noUiSlider. It should be as simple as adding these two lines in range-slider.js exactly as you're capturing the **change** event.

    this.$().on("slide", function() {
      _this.sendAction("slide", _this.slider.val());
    });
    this.$().on("set", function() {
       _this.sendAction("set", _this.slider.val());
    });

You'll then be able to do something like this:

    {{range-slider start=model.defaultStart range=model.defaultRange change="changeFired" slide="slideFired" set="setFired"}}

I tried forking to do a pull request but my clone doesn't like your use of "modelFor" in the example documentation so stopped.

I've verified this functionality works in a local extension of your component.

**Comment by kennethkalmer** [comment]
Thanks for the suggestion @timrwilliams! I'll get cracking on this quickly and get a version up for testing. I'd like to know which part of the docs need love so I can fix that too!

**Comment by kennethkalmer** [comment]
@timrwilliams I hooked up the _slide_ event, check the docs in b81d26d592 for some examples. If this looks good I'll cut a release, and then we need to chat through the _set_ event. I'm not really sure if that is applicable in an Ember context...

**Comment by snc** [comment]
Nice, I'm looking for this feature, too :+1:

**Comment by kennethkalmer** [comment]
Great stuff! Let me know if you'll are happy with the API for _slide_ so I can publish before the weekend, and then we can discuss _set_. In my tired state I did everything on master last night, so no PR :(

**Comment by timrwilliams** [comment]
Looks good, kudos for creating new docs too. To be honest I'm only using the **slide** event so don't have any concerns leaving out **set** until somebody comes up with a real world use case.

**Comment by kennethkalmer** [comment]
Just pushed up 0.4.0 up to npm with the _slide_ action. Thanks for the prod and the feedback!

**Comment by IsaiahJTurner** [comment]
How do I set the value? I tried changing the "start" value but that doesn't seem to update the slider.
