### ISSUE TITLE
With incorrect properties slider is not rendered. With no error messages.

### ISSUE THREAD

**Issue by tikijian** [kennethkalmer/ember-cli-nouislider#34]
When call to `noUiSlider.create()`  method failing inside a component `setup()` function, 
component itself not being rendered. Bad thing, that it's failing silently, without any errors in console.

``` javascript
  setup: on('didInsertElement', function() {
    let $this = this.$().get(0);
    let properties = this.getProperties(
      'start', 'step', 'margin',
      'limit', 'range', 'connect',
      'orientation', 'direction',
      'behaviour', 'animate', 'snap',
      'pips', 'format'
    );
    let sliderEvents = Ember.A(['change', 'set', 'slide', 'update', 'start', 'end']);

    noUiSlider.create($this, properties);

    console.log('Hello world'); // <--- not executed!
```

Wrapping

``` javascript
    try {
      noUiSlider.create($this, properties);
    } catch(e) {
      console.error(e);
    }
```

looks like a good quickfix.

![2016-09-30 10 47 59](https://cloud.githubusercontent.com/assets/1406569/18984469/694d87fc-86fb-11e6-863a-114d430128cc.png)

**Comment by kennethkalmer** [comment]
Thanks for letting me know! I saw some errors in the console locally while merging some new PR's, but this does look good

**Comment by kennethkalmer** [comment]
Apologies for dragging my feet on this, it will go out in the next release!
