### ISSUE TITLE
Tooltips don't appear

### ISSUE THREAD

**Issue by allthesignals** [kennethkalmer/ember-cli-nouislider#42]
Using Ember 2.9
```
              {{range-slider start=(array valueMin valueMax)
                             range=(hash min=0 max=10000000)
                             tooltips=true
                             connect=true
                             step=1
                             on-change="updateRanges"
              }}
```
Tooltips don't seem to appear

![screen shot 2017-01-16 at 4 16 09 pm](https://cloud.githubusercontent.com/assets/5004319/21999255/210dbf0a-dc07-11e6-80d9-eb95e9aee05e.png)

Think this is an issue with Ember 2.9?

**Comment by allthesignals** [comment]
Turned out to be a weird CSS issue.

**Comment by tchan** [comment]
Any idea on how to get the tooltip to look something similar to 
https://refreshless.com/nouislider/examples/ ?
I'm struggling to show 0/1 decimal places
