### ISSUE TITLE
#44 breaks implementations based on nouislider ^9.0

### ISSUE THREAD

**Issue by hoboman313** [kennethkalmer/ember-cli-nouislider#45]
#44 was not implemented properly as npm forces the ~8 version of uislider for the lib and does not allow the lib user to override it inside their package.json ( as was the case with bower ). Please change "nouislider": "~8.5.1" to "nouislider": ">=8.5.1"

**Comment by kennethkalmer** [comment]
Argh, thanks for reporting! Let me just test it with the latest version and then see how to setup an ember-try scenario for the latest 8.5.x, 8.x and 9.x scenarios.

The tests are very lacking at the moment, but I just want the right foundation for them in place.

**Comment by kennethkalmer** [comment]
Actually, having a look now I saw 9.x has been out since September already and according to the release notes there shouldn't be any breaking changes... If all goes well I'll just bump the minimum version to 9.2.0

**Comment by kennethkalmer** [comment]
@hoboman313 just released 0.13.0 with nouislider dependency bumped to "^9.2.0". Thanks for reporting, and sorry for the inconvenience caused.

**Comment by hoboman313** [comment]
Good stuff. Thx for the quick turnaround.
