### ISSUE TITLE
Can many RangeSliders share the same action?

### ISSUE THREAD

**Issue by chriswhong** [kennethkalmer/ember-cli-nouislider#49]
I am currently trying to use a generic action to handle many range sliders.  The `on-change` option specifies the action, but I have no way of knowing which range slider triggered the action.  Is there any way to pass another argument to the action to identify which slider the user is interacting with?

**Comment by chriswhong** [comment]
I think my workaround will probably just be to wrap the range slider in a new component, so I can hijack the action.

**Comment by kennethkalmer** [comment]
Hmm, interesting idea. I have to ask though, would multiple actions not work better as it is very explicit what is going on? Or is this a case of many sliders added dynamically to the page (ie operating on items in a collection)?

**Comment by chriswhong** [comment]
The issue is we may have 50 of these things on the page, and the action would just be doing the same thing for all 50 (updating a range array for a specific item in a collection).  

I was able to wrap `range-slider` in a simple component, and pass in an id to the component.  It works like a charm, but would be nice to have in the range slider.

**Comment by aariabov** [comment]
You can pass argument id of action:
`{{range-slider ... on-change=(action 'rangeSliderChanged' id)}}`
And take it in action:
`rangeSliderChanged(id, val) {
...            
}`

**Comment by scottkidder** [comment]
Seems like this can be closed.
