### ISSUE TITLE
noUi-background element nonexistent?

### ISSUE THREAD

**Issue by hybridmuse** [kennethkalmer/ember-cli-nouislider#51]
Hi, in the original noUiSlider there's an element classed 'noUi-background' that can be used to color the slider's background (to make it contrast with the base). It's used on the Ember noUiSlider docs but the element can't be found when I actually use it. Am I just missing it somehow? Thanks

**Comment by kennethkalmer** [comment]
The `.noUi-background` class got removed in [version 9.0.0](https://github.com/leongersen/noUiSlider/blob/13f79d3d062c69f7174f44a5a6a7451babd4df0c/README.md#900-2016-09-26) of nouislider. You should use `.noUi-target` instead.
