### ISSUE TITLE
Deprecation warning - Scheduling into the 'sync' run loop queue

### ISSUE THREAD

**Issue by Techn1x** [kennethkalmer/ember-cli-nouislider#53]
I've upgraded to Ember 3.0.0 and it seems this addon now causes a deprecation warning (although I jumped from 2.16 -> 3.0.0, so it could have been any version in between)

![capture](https://user-images.githubusercontent.com/1049837/36400034-51526fa0-161a-11e8-8578-3e902daca423.PNG)

Seems to happen when a slider is rendered on the page (don't even need to interact with it). The deprecation points to this section of code (makes sense):
https://github.com/kennethkalmer/ember-cli-nouislider/blob/master/addon/components/range-slider.js#L77-L89

I did a quick google search and couldn't actually find information on this deprecation anywhere...

**Comment by willviles** [comment]
I've got the same after - funnily enough - doing an upgrade from `2.16` -> `3.0.0`.

**Comment by Techn1x** [comment]
It looks like this will be fixed anyway, when 1.0 of this addon is released
https://github.com/kennethkalmer/ember-cli-nouislider/pull/52

**Comment by kennethkalmer** [comment]
Thanks for reporting, I'm gonna keep this open for others to find until #52 is merged in.

Could I ask you a favor please, could you help review and give some feedback over there if needed. I want as many eyes on this as possible!

**Comment by kennethkalmer** [comment]
This has been published to npm as 1.0.0-rc.2, please test with ember install `ember-cli-nouislider@next` and please open any issues that you encounter.

**Comment by Techn1x** [comment]
Thanks @kennethkalmer the update works well, and no more deprecation warning :)
