### ISSUE TITLE
Unexpected range values when setting step

### ISSUE THREAD

**Issue by jleja** [kennethkalmer/ember-cli-nouislider#65]
I'm trying to set up a range slider using this addon, and noticed that, when setting the `step` option, that it sets the range steps to unexpected values.  For my particular case, I'm trying to set up a slider with a `min=0` and `max=18`.  If I set `step=1`, then I'd expect whole numbers (1, 2, 3, etc.) for the entire range, but instead, some values are displaying as floats.

To reproduce:
- Started a brand new Ember project
- Installed `ember-cli-nouislider`
- Added the following to the main template:
```
{{range-slider
  step=1
  start=2
  min=0
  max=18
  connect=true
  tooltips=true
}}

{{range-slider
  step=1
  start=2
  min=1
  max=18
  connect=true
  tooltips=true
}}

{{range-slider
  step=1
  start=2
  min=2
  max=18
  connect=true
  tooltips=true
}}
```

The last range slider shows whole numbers for the entire range, but the first two start to show non-whole numbers at various steps.  I've also included sliders created with `nouislider.js` directly to see if the issue was with the base slider or the Ember addon:
![screen shot 2018-05-17 at 4 07 08 pm](https://user-images.githubusercontent.com/1759897/40201202-664cbdc8-59ec-11e8-8e4c-ead890483a18.png)

**Comment by jleja** [comment]
Figured out a workaround for this, which was to simply override the `formatTo` and `formatFrom` formatters.

**Comment by Dzieni** [comment]
Workaround is not a solution. Could this one be reopened, please?
