### ISSUE TITLE
Property 'padding' is not passed to nouislider

### ISSUE THREAD

**Issue by annaemu** [kennethkalmer/ember-cli-nouislider#69]
Property 'padding' is not passed to nouislider and subsequently usage of that with this addon does not work. https://refreshless.com/nouislider/slider-options/#section-padding

**Comment by scottkidder** [comment]
This has been added in #62 and will hopefully get merged soon. I'm using it and it works as expected.

**Comment by kennethkalmer** [comment]
This has been added, I'm preparing a new release.
