### ISSUE TITLE
Build Bower package

### ISSUE THREAD

**Issue by carsomyr** [kennethkalmer/ember-cli-nouislider#7]
Hi, have you considered making `rangeslider.js` independent of Ember CLI? Not all of us use it because of the half-working transpiler and opinionated asset pipeline. I was wondering if you could provide a version of the file in as a standard RequireJS module that only uses AMD when it's detected:

```
if ( typeof define === "function" && define.amd ) {
    define("ember-cli-nouislider", [], function() {
        return rangeSlider;
    });
} else {
    window.rangeSlider = rangeSlider;
}
```

**Comment by kennethkalmer** [comment]
I'll have to do some research, but this does sound like a reasonable request!

**Comment by kennethkalmer** [comment]
Given how the ember landscape has now really embraced ember-cli, and even the notion that ember itself could just become an ember-cli addon (ember-data already is), I don't think this is worth pursuing anymore.

If this is still relevant, please open a PR with support for this.

Thanks for the feedback!
