### ISSUE TITLE
Deprecation warnings:

### ISSUE THREAD

**Issue by petermanders89** [kennethkalmer/ember-cli-nouislider#76]
Currently we are using ember version 3.10 and we get these deprecation warnings: 

- The <component:range-slider::ember6391>#range computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.

- The <component:range-slider::ember6391>#format computed property was just overriden. This removes the computed property and replaces it with a plain value, and has been deprecated. If you want this behavior, consider defining a setter which does it manually.

Further information about these deprecations can be found [here](https://emberjs.com/deprecations/v3.x#toc_computed-property-override)

**Comment by Zeeyed** [comment]
I already faced this deprecation and this is how I fix it.

Instead of passing `range` and `format` props to your `nouislider-component` as computed properties, try to pass `min, max, from, to` props. Then where you defined your `nouislider-component` create `range` and `format` as setters.

Passing down your properties when you call your component
```.js
{{nouislider-component
    start=start
    connect=true
    min=min
    max=max
    from=from
    to=to
}}
```

Where you defined your `nouislider-component.js`
```.js
range: computed('min', 'max', {
    get(key) {
        if(this.get(`_${key}`) {
            return this.get(`_${key}`);
        }
        return {
            min: this.get('min') || 0,
            max: this.get('max') || 100
	};
    },
    set(key, value) {
        return this.set(`_${key}`, value);
    }
}),
// ... do the same to `format` prop
```

**Comment by petermanders89** [comment]
Closing this issue, seems to be a wrong implementation on my end.  Was doing the following: 

```
  <RangeSlider @range={{this.range}}
               @start={{this.start}}
               @connect={{this.connect}}
               @format={{this.sliderFormat}}
  />
```

Should've done the following:

```
  <RangeSlider @start={{this.start}}
               @min={{this.min}}
               @max={{this.max}}
               @connect={{this.connect}}
               @formatTo={{this.sliderFormat.to}}
               @formatFrom={{this.sliderFormat.from}}
  />
```
